name: "cliche action"
description: "Generates a static site with cliche and creates an artifact."
author: "gdtroszak"
inputs:
  name:
    description: "Artifact name"
    required: false
    default: "cliche-site"
  content-path:
    description: "Path to the site content."
    required: false
    default: "content"
  header-path:
    description: "Path to the site header."
    required: false
    default: "header.md"
  footer-path:
    description: "Path to the site footer."
    required: false
    default: "footer.md"
  style-path:
    description: "Path to the site style."
    required: false
    default: "style.css"
  domain:
    description: "Domain where the site will be hosted."
    required: false
  base-url:
    description: "A base url that the site will be served from."
    required: false
outputs:
  artifact-id:
    description: "The ID of the artifact that was uploaded."
    value: ${{ steps.upload-artifact.outputs.artifact-id }}
runs:
  using: composite
  steps:
    - name: rust setup
      uses: dtolnay/rust-toolchain@stable
    - name: cache cliche
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cliche-1.2.0
        restore-keys: |
          ${{ runner.os }}-cliche-
    - name: install dependencies
      shell: bash
      run: cargo install cliche --version "1.2.0"
    - name: build site
      shell: bash
      run: |
        DOMAIN_ARG=""
        if [ -n "${{ inputs.domain }}" ]; then
          DOMAIN_ARG="--domain=${{ inputs.domain }}"
        fi

        BASE_URL_ARG=""
        if [ -n "${{ inputs.base-url }}" ]; then
          BASE_URL_ARG="--base-url=${{ inputs.base-url }}"
        fi
        
        cliche ${{ inputs.content-path }} \
          --header=${{ inputs.header-path }} \
          --footer=${{ inputs.footer-path }} \
          --style=${{ inputs.style-path }} \
          $DOMAIN_ARG \
          $BASE_URL_ARG
    - name: upload artifact
      id: upload-artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: './_site'
